import type { RetroPreset, RetroSettings } from '../types/retro';

export const DEFAULT_SETTINGS: RetroSettings = {
  brightness: 0,
  contrast: 1,
  saturation: 1,
  warmth: 0,
  tint: 0,
  fade: 0,
  sepia: 0,
  monochrome: 0,
  filmGrain: 0,
  grainSize: 1.2,
  vignette: 0,
  vignetteRoundness: 0.8,
  seed: 42,
  dustScratches: 0,
  lightLeak: 0,
  lightLeakHue: 35,
  lightLeakPosition: 0,
  chromaticAberration: 0,
  bloomGlow: 0,
  scanlines: 0,
  pixelation: 0,
  dither: 0,
  lensBlur: 0,
  dateStamp: {
    enabled: false,
    text: '',
    format: 'auto-decade',
    customDate: '',
    color: 'orange',
    fontStyle: 'lcd7',
    position: 'bottom-right',
    size: 1.0,
  },
  frame: 'none',
  vhsOsd: false,
};

export const RETRO_PRESETS: RetroPreset[] = [
  // --- 1960s ---
  {
    id: '60s-kodachrome',
    name: '1960s Kodachrome',
    decade: '1960s',
    subtitle: 'Klassischer 60er Farbdruck',
    description: 'Warme Vintage-Töne, samtige Schatten, sattes Gelb-Rot-Spektrum mit feinstem analogem Korn.',
    iconName: 'Camera',
    tags: ['Vintage', 'Warm', 'Kodak', '60er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.05,
      contrast: 1.15,
      saturation: 1.2,
      warmth: 0.35,
      tint: 0.1,
      fade: 0.15,
      sepia: 0.15,
      monochrome: 0,
      filmGrain: 0.45,
      grainSize: 1.3,
      vignette: 0.45,
      dustScratches: 0.3,
      lightLeak: 0.35,
      lightLeakHue: 38,
      bloomGlow: 0.25,
      chromaticAberration: 0.15,
      frame: 'slide6x6',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: false,
      },
    },
  },
  {
    id: '60s-silver-halide',
    name: '1960s Silver Monochrome',
    decade: '1960s',
    subtitle: 'Silberhalogenid Schwarz-Weiß',
    description: 'Dramatischer Schwarzweißfilm der 1960er mit kräftigem Mikrokontrast, Filmkratzern und Filmkorn.',
    iconName: 'Film',
    tags: ['B&W', 'Silber', 'Klassisch', '60er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.02,
      contrast: 1.35,
      saturation: 0,
      warmth: 0.08,
      tint: 0,
      fade: 0.2,
      sepia: 0.08,
      monochrome: 1,
      filmGrain: 0.65,
      grainSize: 1.6,
      vignette: 0.6,
      dustScratches: 0.55,
      lightLeak: 0.2,
      lightLeakHue: 50,
      bloomGlow: 0.3,
      chromaticAberration: 0.05,
      frame: 'film35mm',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: false,
      },
    },
  },

  // --- 1970s ---
  {
    id: '70s-polaroid',
    name: '1970s Instant Polaroid',
    decade: '1970s',
    subtitle: 'SX-70 Sofortbild-Ästhetik',
    description: 'Charakteristischer Polaroid-Look mit weichen Schatten, cremigem Gelbstich, Weißrand und Lichtfleck.',
    iconName: 'Image',
    tags: ['Polaroid', 'Sofortbild', 'Warm', '70er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.08,
      contrast: 1.1,
      saturation: 1.1,
      warmth: 0.45,
      tint: -0.15,
      fade: 0.28,
      sepia: 0.2,
      monochrome: 0,
      filmGrain: 0.5,
      grainSize: 1.4,
      vignette: 0.5,
      dustScratches: 0.4,
      lightLeak: 0.55,
      lightLeakHue: 28,
      lightLeakPosition: 1,
      bloomGlow: 0.35,
      chromaticAberration: 0.2,
      frame: 'polaroid',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: false,
      },
    },
  },
  {
    id: '70s-disco-fever',
    name: '1970s Disco Gold',
    decade: '1970s',
    subtitle: 'Super 8 & Golden Hour',
    description: 'Sonnenverwöhnte Bernsteintöne der 70er Jahre, weicher Lichteinfall und verträumte Farbbalance.',
    iconName: 'Sun',
    tags: ['Super 8', 'Golden Hour', 'Cinema', '70er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.05,
      contrast: 1.18,
      saturation: 1.35,
      warmth: 0.55,
      tint: 0.12,
      fade: 0.22,
      sepia: 0.25,
      monochrome: 0,
      filmGrain: 0.42,
      grainSize: 1.2,
      vignette: 0.4,
      dustScratches: 0.35,
      lightLeak: 0.6,
      lightLeakHue: 42,
      lightLeakPosition: 0,
      bloomGlow: 0.4,
      chromaticAberration: 0.25,
      lensBlur: 0.2,
      frame: 'none',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: false,
      },
    },
  },

  // --- 1980s ---
  {
    id: '80s-vhs-camcorder',
    name: '1980s VHS Camcorder',
    decade: '1980s',
    subtitle: 'Magnetband & CRT Scanlines',
    description: 'Authentischer VHS-Band-Look mit horizontalen Scanlines, Farbverschiebung (RGB Glitch) und PLAY OSD.',
    iconName: 'Tv',
    tags: ['VHS', 'Video', 'Scanlines', 'Glitch', '80er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.04,
      contrast: 1.22,
      saturation: 1.28,
      warmth: -0.1,
      tint: 0.2,
      fade: 0.18,
      sepia: 0,
      monochrome: 0,
      filmGrain: 0.55,
      grainSize: 1.8,
      vignette: 0.35,
      dustScratches: 0.25,
      lightLeak: 0.25,
      lightLeakHue: 310,
      chromaticAberration: 0.65,
      bloomGlow: 0.45,
      scanlines: 0.7,
      pixelation: 0.15,
      frame: 'vhs',
      vhsOsd: true,
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: true,
        text: 'OCT. 24 1985',
        format: 'auto-decade',
        color: 'white',
        fontStyle: 'digital',
        position: 'bottom-left',
        size: 0.9,
      },
    },
  },
  {
    id: '80s-synth-neon',
    name: '1980s Synthwave Arcade',
    decade: '1980s',
    subtitle: 'Neon Magenta & Cyan Cross-Process',
    description: 'Elektrisierender Neon-Kontrast, kräftige Magentatöne und kühle Schatten mit Glüh-Effekt.',
    iconName: 'Zap',
    tags: ['Synthwave', 'Neon', 'Arcade', '80er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.02,
      contrast: 1.35,
      saturation: 1.45,
      warmth: -0.25,
      tint: 0.45,
      fade: 0.1,
      sepia: 0,
      monochrome: 0,
      filmGrain: 0.35,
      grainSize: 1.0,
      vignette: 0.55,
      dustScratches: 0.15,
      lightLeak: 0.5,
      lightLeakHue: 295,
      chromaticAberration: 0.5,
      bloomGlow: 0.5,
      scanlines: 0.4,
      frame: 'crt',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: true,
        text: '12-08-1988',
        format: 'auto-decade',
        color: 'yellow',
        fontStyle: 'lcd7',
        position: 'bottom-right',
        size: 1.0,
      },
    },
  },

  // --- 1990s ---
  {
    id: '90s-disposable-cam',
    name: '1990s Einwegkamera (Disposable)',
    decade: '1990s',
    subtitle: '35mm Urlaubs-Kompaktkamera',
    description: 'Der ikonische 90er Schnappschuss-Look mit Blitz-Reflex, orangenem LED-Datumsstempel und Fujicolor-Tönen.',
    iconName: 'Sparkles',
    tags: ['Einwegkamera', '35mm', 'Datumsstempel', '90er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.06,
      contrast: 1.25,
      saturation: 1.25,
      warmth: 0.22,
      tint: -0.08,
      fade: 0.12,
      sepia: 0.05,
      monochrome: 0,
      filmGrain: 0.52,
      grainSize: 1.3,
      vignette: 0.42,
      dustScratches: 0.45,
      lightLeak: 0.4,
      lightLeakHue: 32,
      lightLeakPosition: 2,
      chromaticAberration: 0.25,
      bloomGlow: 0.3,
      frame: 'none',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: true,
        text: "'96 07 18",
        format: 'auto-decade',
        color: 'orange',
        fontStyle: 'lcd7',
        position: 'bottom-right',
        size: 1.1,
      },
    },
  },
  {
    id: '90s-grunge-faded',
    name: '1990s Grunge Lo-Fi',
    decade: '1990s',
    subtitle: 'Abgenutzter CD-Cover & Zine Look',
    description: 'Entsättigte Mitten, angehobene Grüntöne in den Tiefen, matter Schwarzpunkt und sichtbare Filmabnutzung.',
    iconName: 'Flame',
    tags: ['Grunge', 'Lo-Fi', 'Matte', '90er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: -0.02,
      contrast: 1.12,
      saturation: 0.85,
      warmth: 0.1,
      tint: -0.22,
      fade: 0.35,
      sepia: 0.12,
      monochrome: 0,
      filmGrain: 0.6,
      grainSize: 1.5,
      vignette: 0.5,
      dustScratches: 0.6,
      lightLeak: 0.3,
      lightLeakHue: 48,
      chromaticAberration: 0.3,
      bloomGlow: 0.2,
      frame: 'film35mm',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: true,
        text: "'94 11 03",
        format: 'auto-decade',
        color: 'red',
        fontStyle: 'dotmatrix',
        position: 'bottom-right',
        size: 1.0,
      },
    },
  },

  // --- 2000s ---
  {
    id: '00s-early-digicam',
    name: '2000s CCD Digicam (Y2K)',
    decade: '2000s',
    subtitle: 'Cyberpunk & 3.2 Megapixel CCD Sensor',
    description: 'Scharfer digitaler Sensor-Look der 2000er mit kühlen Blautönen, harter Blitzüberstrahlung und digitalem Rauschen.',
    iconName: 'Laptop',
    tags: ['Y2K', 'Digicam', 'CCD', '2000er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.08,
      contrast: 1.28,
      saturation: 1.32,
      warmth: -0.2,
      tint: 0.08,
      fade: 0.05,
      sepia: 0,
      monochrome: 0,
      filmGrain: 0.28,
      grainSize: 0.8,
      vignette: 0.22,
      dustScratches: 0.08,
      lightLeak: 0.15,
      lightLeakHue: 195,
      chromaticAberration: 0.38,
      bloomGlow: 0.55,
      pixelation: 0.2,
      dither: 0.2,
      frame: 'none',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: true,
        text: '2003/04/19',
        format: 'auto-decade',
        color: 'yellow',
        fontStyle: 'digital',
        position: 'bottom-right',
        size: 0.95,
      },
    },
  },
  {
    id: '00s-flip-phone',
    name: '2000s Flip Phone VGA',
    decade: '2000s',
    subtitle: 'Klapphandy VGA & Dithering',
    description: 'Extremer Y2K-Retro-Look mit grober Pixelraster-Auflösung, Bayer-Dithering und reduzierter Farbtiefe.',
    iconName: 'Smartphone',
    tags: ['Klapphandy', 'VGA', 'Pixel', 'Dither', '2000er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.05,
      contrast: 1.35,
      saturation: 1.1,
      warmth: -0.1,
      tint: -0.1,
      fade: 0.1,
      sepia: 0,
      monochrome: 0,
      filmGrain: 0.2,
      grainSize: 0.8,
      vignette: 0.3,
      dustScratches: 0.05,
      lightLeak: 0.1,
      lightLeakHue: 210,
      chromaticAberration: 0.45,
      bloomGlow: 0.2,
      pixelation: 0.65,
      dither: 0.6,
      frame: 'none',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: false,
      },
    },
  },

  // --- 2010s ---
  {
    id: '10s-early-instagram',
    name: '2010s Early Instagram Lo-Fi',
    decade: '2010s',
    subtitle: 'Vintage Hipster & Tilt-Shift',
    description: 'Die Anfänge der Foto-Apps 2010–2012: Extreme Vignettierung, sattes Gelb-Blau-Colorgrading und Miniatur-Unschärfe.',
    iconName: 'Layers',
    tags: ['Instagram', 'Lo-Fi', 'Hipster', 'Tilt-Shift', '2010er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.02,
      contrast: 1.32,
      saturation: 1.38,
      warmth: 0.28,
      tint: 0.15,
      fade: 0.16,
      sepia: 0.15,
      monochrome: 0,
      filmGrain: 0.3,
      grainSize: 1.0,
      vignette: 0.68,
      vignetteRoundness: 0.9,
      dustScratches: 0.1,
      lightLeak: 0.35,
      lightLeakHue: 40,
      lightLeakPosition: 3,
      chromaticAberration: 0.2,
      bloomGlow: 0.25,
      lensBlur: 0.45,
      frame: 'polaroid',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: false,
      },
    },
  },
  {
    id: '10s-toaster-warm',
    name: '2010s Toaster Sunset',
    decade: '2010s',
    subtitle: 'Rötliche Randverbrennung & Pfirsich-Glanz',
    description: 'Ikonischer 2011er Filter mit glühend warmem Zentrum, getoasteten roten Rändern und verträumter Vignette.',
    iconName: 'SunMedium',
    tags: ['Toaster', 'Retro App', 'Sunset', '2010er'],
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 0.04,
      contrast: 1.25,
      saturation: 1.2,
      warmth: 0.42,
      tint: 0.25,
      fade: 0.2,
      sepia: 0.22,
      monochrome: 0,
      filmGrain: 0.25,
      grainSize: 1.1,
      vignette: 0.6,
      dustScratches: 0.12,
      lightLeak: 0.5,
      lightLeakHue: 15,
      lightLeakPosition: 0,
      chromaticAberration: 0.18,
      bloomGlow: 0.35,
      lensBlur: 0.3,
      frame: 'minimal-white',
      dateStamp: {
        ...DEFAULT_SETTINGS.dateStamp,
        enabled: false,
      },
    },
  },
];
